### ISSUE TITLE
Pinecone API key AttributeError: 'str' object has no attribute 'resolve_value'

### ISSUE THREAD

**Issue by Gach-omba** [vrunm/pinecone-haystack#1]
Hello. I am working on a project where we are migrating to pinecone vector db and we are using the haystack pipeline. I have run into the error   AttributeError: 'str' object has no attribute 'resolve_value'
I am using haystack version 2.0 on google colab
I have tried creating an environment variable for the pinecone API key and also tried using it directly but I still get the same error.
The sample code where I am getting the error is as follows :

                          document_store = PineconeDocumentStore(
                              metric="cosine",
                              dimension=768,
                              index="our_demo_index",                              
                              environment="us-west1-gcp",
                              api_key=os.environ.get("PINECONE_API_KEY") or "pinecone-test-key" # Explicitly set the environment
                          )

The complete error message log is : 
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-13-3ae998c6d198>](https://localhost:8080/#) in <cell line: 1>()
----> 1 document_store = PineconeDocumentStore(
      2     metric="cosine",
      3     dimension=768,
      4     index="our_demo_index",
      5 

[/usr/local/lib/python3.10/dist-packages/haystack_integrations/document_stores/pinecone/document_store.py](https://localhost:8080/#) in __init__(self, api_key, environment, index, namespace, batch_size, dimension, **index_creation_kwargs)
     59 
     60         """
---> 61         resolved_api_key = api_key.resolve_value()
     62         if resolved_api_key is None:
     63             msg = (

AttributeError: 'str' object has no attribute 'resolve_value'

**Comment by vrunm** [comment]
@Gach-omba This integration for Haystack has been updated and migrated to [Haystack Core Integrations](https://github.com/deepset-ai/haystack-core-integrations). 

Please refer to this page for more information: 
https://haystack.deepset.ai/integrations/pinecone-document-store

Updating to the latest version should resolve the problem you are facing. You can install the latest version using:  
 `pip install pinecone_haystack`

**Comment by Gach-omba** [comment]
Okay. Thanks @vrunm for your help
